### ISSUE TITLE
basal/bolus data shows 3 hours early in PT

### ISSUE THREAD

**Issue by rwyler** [jwoglom/tconnectsync-heroku#1]
For user in PT time zone, on nightscout UX, it's displaying CGM info at correct time (e.g., 4pm PT) (from dexcom's api), but displaying (controliq) Bolus/Basal info (from tconnect's api) as having happened 3 hours earlier (eg., a 4pm PT bolus appears as happening at 1pm PT).  Suspect timezone conversion problem with getting the tconnect bolus/basal info and pushing it to the nightscout db. Using tconnectsync-heroku with no modifications. Any fix/help would be appreciated. Thanks

**Comment by jwoglom** [comment]
Hey @rwyler, I'm going to move this issue to the tconnectsync GitHub issues page rather than tconnectsync-heroku since this relates to the synchronization component of tconnectsync: https://github.com/jwoglom/tconnectsync/issues/28
