### ISSUE TITLE
Updating using CLI

### ISSUE THREAD

**Issue by craigpress** [jwoglom/tconnectsync-heroku#10]
I was trying to run the update in process and I am getting an error. Is this due to the new two factor authentication issue with salesforce or something else?  I thought it might be my computer, but tried this on my PC and MAC. both getting basically the same error. 

"ID a6e32379-4ad5-408e-b82a-0fcca79aad45
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/python
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     Python has released a security update! Please consider upgrading to python-3.9.12
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
cp: cannot stat '/tmp/build_24bb7b62/requirements.txt': No such file or directory
-----> Using cached install of python-3.9.9
-----> Installing pip 22.0.4, setuptools 60.10.0 and wheel 0.37.1
-----> Installing dependencies with Pipenv 2020.11.15
       Installing dependencies from Pipfile.lock (97010d)...
       error in Flask-APScheduler setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; super(type, obj): obj must be an instance or subtype of type
 !     Push rejected, failed to compile Python app.
 !     Push failed"

**Comment by jwoglom** [comment]
Interesting, this looks like an issue with the version of python running inside the Heroku environment, probably? This post suggests it might be an older version of setuptools: https://github.com/sdispater/pendulum/issues/187#issuecomment-375820769 The requirements for which the app should run inside Heroku specify a fairly recent version of setuptools, though.

Maybe try updating the runtime to `python-3.9.12` like it mentions (change `runtime.txt`) before trying to update via the CLI. Also, do note that outside of your configuration options, tconnectsync doesn't store any data or state, so you can safely delete the heroku app and recreate it again if the updating isn't working.

I'll also try and replicate from my end.

**Comment by craigpress** [comment]
I did what you suggested at the end, which was to delete the app and recreated it. I think it may have solved my time sync issue also.

Craig

From: James Woglom ***@***.***>
Reply-To: jwoglom/tconnectsync-heroku ***@***.***>
Date: Monday, April 18, 2022 at 3:14 PM
To: jwoglom/tconnectsync-heroku ***@***.***>
Cc: Craig Press ***@***.***>, Author ***@***.***>
Subject: Re: [jwoglom/tconnectsync-heroku] Updating using CLI (Issue #10)


Interesting, this looks like an issue with the version of python running inside the Heroku environment, probably? This post suggests it might be an older version of setuptools: sdispater/pendulum#187 (comment)<https://github.com/sdispater/pendulum/issues/187#issuecomment-375820769> The requirements for which the app should run inside Heroku specify a fairly recent version of setuptools, though.

Maybe try updating the runtime to python-3.9.12 like it mentions (change runtime.txt) before trying to update via the CLI. Also, do note that outside of your configuration options, tconnectsync doesn't store any data or state, so you can safely delete the heroku app and recreate it again if the updating isn't working.

I'll also try and replicate from my end.
