### ISSUE TITLE
Documentation edits

### ISSUE THREAD

**Issue by jenm999** [jwoglom/tconnectsync-heroku#2]
Hi! I edited the readme to make it more comprehensible to the music majors among us. :) Attached. Happy to help further troubleshooting. This is so brilliant and has already helped me avoid bothering my kiddo at school this morning. Thank you!
[TConnectSync-for-Heroku.docx](https://github.com/jwoglom/tconnectsync-heroku/files/7809366/TConnectSync-for-Heroku.docx)

**Comment by jwoglom** [comment]
Thanks for the suggestions! I've added some clarifying information into the readme. Please let me know if any of it seems confusing or could use clarification!

**Comment by jenm999** [comment]
It looks great. My main confusion was heroku.io vs herokuapp.com. Maybe a
note that Uptime Robot is not part of the app, just pings it to keep it
active? But people will still have questions and can turn to the facebook
group. Thanks so much for doing this!

Question: is it pulling IOB from tconnect or just doing the math?

Also, I see that it pulls basal rates from tconnect but you need to input
the rates in nightscout for the basal adjustments to render faithfully. My
son has two different profiles (he needs less insulin at school which is
weird) so I need to remember to switch profiles in nightscout on Monday
mornings. Might be worth making a note in the readme about this.

Thanks again for your work on this!

Best,

Jen








Jennifer Montbach

**Comment by jwoglom** [comment]
The heroku.io vs herokuapp.com was a typo on my end. Can add a sentence to explain uptimerobot's purpose.

The IOB that is displayed in Nightscout is, I believe, calculated by Nightscout. However, tconnectsync does send the pump's IOB value into Nightscout as an "activity" field, Nightscout just doesn't show it. It might be worth chatting with the Nightscout folks in the future to see whether they can read in that value or use it to adjust their computations.

As for basal rates, keeping the nightscout values in sync with the pump's sounds like a great example of something which could be done automatically. I opened https://github.com/jwoglom/tconnectsync/issues/29 to track this

**Comment by jenm999** [comment]
Wish I had any technical know-how to help!

One other item on my wishlist would be to see the pump's battery. That's
shown on the tconnect mobile app but I don't believe it's shown in the
tconnect website so I'm guessing that's a no go.

Feel free to reach out anytime if you want a tester or help with
documentation.

Cheers,

Jen
