### ISSUE TITLE
Load back data from heroku install

### ISSUE THREAD

**Issue by craigpress** [jwoglom/tconnectsync-heroku#4]
Is there a way using the heroku CLI to load back data? 

Also, this is so great since it requires much less tech knowhow to run and update!  Thank you!

**Comment by jwoglom** [comment]
@craigpress You should be able to open the console within the heroku webui and run the `tconnectsync` command with whatever arguments you desire from there. I just checked and it appears to propagate the environment variables through from the heroku configuration.

**Comment by craigpress** [comment]
I tried typing in to the console command: tconnectsync --start-date 2021-10-01 --end-date 2022-01-01
It says: "bash: tconnectsync: command not found"

**Comment by jwoglom** [comment]
Try entering the default `bash` as the console command, and then type tconnectsync inside the bash prompt. That seemed to work for me

**Comment by craigpress** [comment]
That worked. Thanks
