### ISSUE TITLE
Basal data appears to be shifted by about 2 hours. 

### ISSUE THREAD

**Issue by craigpress** [jwoglom/tconnectsync-heroku#5]
It seems like the basal data from the tandem is shifted to about 2 hours later than everything else. The rest of the data seems correct. You can see where there are BG peaks the basal is at it's lowest. I have the profile and tconnect time zones both set to eastern/new york. 
<img width="1431" alt="Screen Shot 2022-01-10 at 8 39 15 AM" src="https://user-images.githubusercontent.com/22849559/148775553-45bd6b73-4160-4c6e-87ae-844938fb4d3f.png">

**Comment by jwoglom** [comment]
Hi Craig,

Would you mind going to https://YOUR-HEROKU-APP-NAME.herokuapp.com/check_login?secret=YOUR_TCONNECTSYNC_SECRET_KEY, and emailing the contents of the page to me? (email is j [at] wogloms.net). This gives some diagnostic information that I can use to try and troubleshoot your issue.

Without having seen that yet, the only recommendation I can suggest is checking that you have `TIMEZONE_NAME` set in the Heroku environment variables as `America/New_York`

Thanks.

**Comment by jwoglom** [comment]
Closing this issue. Please re-open at https://github.com/jwoglom/tconnectsync/issues if it continues.
