### ISSUE TITLE
Hello!  Deploy to Heroku goes a to a page that says Page Not Found

### ISSUE THREAD

**Issue by amyvedi** [jwoglom/tconnectsync-heroku#6]
Help!
I already have T:Connect, Nightscout, Heroku and Uptime.
I started to manually add a new App.  Created all the variables.  But I feel like I'm missing something that the "deploy" button would help with. I dunno.

**Comment by jwoglom** [comment]
Hi @amyvedi, did you solve your issue? What was the solution?
