### ISSUE TITLE
TCONNECTSYNC_HEROKU_FEATURES not working

### ISSUE THREAD

**Issue by vin** [jwoglom/tconnectsync-heroku#7]
Hi, I've set `TCONNECTSYNC_HEROKU_FEATURES` to `BASAL,BOLUS,PUMP_EVENTS` but in the logs I still see lines like:

```
2022-03-14T06:08:21.600282+00:00 app[web.1]: call args: [<tconnectsync.api.TConnectApi object at 0x7fa0f07008e0>, <tconnectsync.nightscout.NightscoutApi object at 0x7fa0f07008b0>, datetime.datetime(2022, 3, 13, 6, 8, 13, 172735), datetime.datetime(2022, 3, 14, 6, 8, 13, 172735), False, ['BASAL', 'BOLUS']]
```

I've also tried adding `&features=PUMP_EVENTS` or `&features=BASAL,BOLUS,PUMP_EVENTS` but I see no change in the logs or the observable behavior, e.g.:

https://vin-tconnectsync.herokuapp.com/update?secret=<omitted>&features=PUMP_EVENTS

Can you see what I'm doing wrong? Is there documentation on the best way to debug this sort of thing? I don't know what's the best way to proceed with the thing running on heroku. I suppose I could fork it and add additional logging, but that sounds tedious compared to being able to run and debug it locally.

Thanks!

**Comment by jwoglom** [comment]
Hi @vin, you might've just run into a bug which I just fixed. Feel free to try again with the latest version of tconnectsync-heroku.

You should be able to either specify `?secret=..&features=BASAL,BOLUS,PUMP_EVENTS` in the query string or the `TCONNECTSYNC_HEROKU_FEATURES` environment variable. There was a bug affecting the parsing of both use cases.

**Comment by rankelly** [comment]
Can you clarify the Insulin On Board value?  I am looking at the IOB value on the interface, but it does not match up with what the pump is showing.  I really need for the value to be accurate.

**Comment by jwoglom** [comment]
@rankelly just to clarify are you referring to the IOB value which appears within Nightscout itself, or the "activity" API endpoint for IOB created by tconnectsync?

The former is calculated by Nightscout automatically based on your bolus entries and current profile settings and is what shows up in the Nightscout UI. The latter isn't actually used by the Nightscout interface at all and is an optional setting in case you wanted to show the pump's reported IOB in some kind of custom interface.

So if the Nightscout UI's IOB is wrong then you should change your Nightscout profile settings. https://github.com/jwoglom/tconnectsync/issues/29 tracks adding functionality within tconnectsync to set this automatically, and is a work in progress.

**Comment by rankelly** [comment]
This is in reference to the UI value.  I was previously using the Medtronic pump and I am guessing from your statement that those values were updated and calc'ed automatically.  I never paid attention to that.  I am using your script to bring over the bolus values but I am still seeing a "0.00" value for IOB on the interface.  Is there a certain number of bolus values that are required for this calc or a time period?

**Comment by jwoglom** [comment]
I'm not entirely sure why it would be showing up as blank, but I suspect it's a Nightscout issue. Maybe check that you have iob in the ENABLE string and that your Nightscout delivery profile is set up. You could potentially also ask in the nightscout discord or on facebook.

**Comment by jwoglom** [comment]
Closing issue, please re-open at https://github.com/jwoglom/tconnectsync/issues if this is still an issue.
