### ISSUE TITLE
403 Forbidden Login Error (Seems same as on non-Heroku version?)

### ISSUE THREAD

**Issue by The3D** [jwoglom/tconnectsync-heroku#8]
New to all this, but this error seems to be the same one that has been fixed in the non-heroku version. Could it just need a version update?

tconnectsync version 0.6.5
Python version 3.9.9 (main, Nov 16 2021, 09:53:35) 
[GCC 9.3.0]
System platform linux
Running checks with time range 2022-04-05 16:55:09.549891 to 2022-04-06 16:55:09.549891
Current time: 2022-04-06 16:55:09.550113
time.tzname: ('UTC', 'UTC')
Loading secrets...
TIMEZONE_NAME: America/New_York
-----
Logging in to t:connect ControlIQ API...
Received ApiException in ControlIQApi with endpoint 'summary/users/2fb09233-06cf-4421-823d-21eea61c9c17' (tries 0): ControlIQ API HTTP 404 response: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-97f047764b666844aac6dbc0ea267a13-3bd06d8da286594b-00"} (HTTP 404)
Error occurred querying ControlIQ API:
ControlIQ API HTTP 404 response: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-97f047764b666844aac6dbc0ea267a13-3bd06d8da286594b-00"} (HTTP 404)
Querying ControlIQ therapy_timeline...
ControlIQ therapy_timeline: {'basal': {'profileRates': [], 'tempDeliveryEvents': [], 'algorithmDeliveryEvents': [], 'profileDeliveryEvents': []}, 'events': [], 'suspensionDeliveryEvents': [], 'softwareUpdates': [], 'pumpFeatures': [{'serialNumber': '92442310', 'features': {'controlIQ': {'feature': 1, 'dateTimeFirstDetected': '2021-11-27T15:47:32', 'unixTimestamp': 1638056852}}}, {'serialNumber': '', 'features': {'controlIQ': {'feature': 1, 'dateTimeFirstDetected': '2020-12-08T11:19:47', 'unixTimestamp': 1607455187}}}]}
-----
Logging in to t:connect WS2 API...
WS2 basaliq status: {'BasalIQTech': {'DaysOn': 0, 'HoursOn': 0, 'PercentTimeOn': 0, 'AvgGlucoseOnSuspend': 0, 'PercentSuspendedNight': 0, 'PercentSuspendedDay': 0, 'AverageSuspensionsPerDay': 0, 'AverageSuspensionDuration': 0, 'AverageGlucoseOnResume': 0, 'BiqPercentSetOff': 0, 'BiqDaysSetOff': 0, 'BiqHoursSetOff': 0, 'BiqMinutesSetOff': 0, 'CgmInactivePercent': 0, 'CgmInactiveDays': 0, 'CgmInactiveHours': 0, 'CgmInactiveMinutes': 0, 'PumpInactivePercent': 100, 'PumpInactiveDays': 2, 'PumpInactiveHours': 0, 'PumpInactiveMinutes': 0, 'AvgInactiveDays': 0, 'AvgInactiveHours': 0, 'AvgInactiveMinutes': 0, 'DaysSuspendedNight': 0, 'HoursSuspendedNight': 0, 'MinutesSuspendedNight': 0, 'DaysSuspendedDay': 0, 'HoursSuspendedDay': 0, 'MinutesSuspendedDay': 0}}
Querying WS2 therapy_timeline_csv...
therapy_timeline_csv: %s {'readingData': [], 'iobData': [], 'basalData': [], 'bolusData': []}
-----
Logging in to t:connect Android API...
Error occurred querying Android API:
Received HTTP 403 during login: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
 (HTTP 403)
Querying Android therapy_events...
Error occurred querying Android therapy_events:
Received HTTP 403 during login: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
 (HTTP 403)
-----
Logging in to Nightscout...
Nightscout status: {'status': 'ok', 'name': 'nightscout', 'version': '14.2.2', 'serverTime': '2022-04-06T16:55:16.756Z', 'serverTimeEpoch': 1649264116756, 'apiEnabled': True, 'careportalEnabled': True, 'boluscalcEnabled': True, 'settings': {'units': 'mg/dl', 'timeFormat': 12, 'dayStart': 7, 'dayEnd': 21, 'nightMode': False, 'editMode': True, 'showRawbg': 'never', 'customTitle': 'Nightscout', 'theme': 'colors', 'alarmUrgentHigh': True, 'alarmUrgentHighMins': [30, 60, 90, 120], 'alarmHigh': True, 'alarmHighMins': [30, 60, 90, 120], 'alarmLow': True, 'alarmLowMins': [15, 30, 45, 60], 'alarmUrgentLow': True, 'alarmUrgentLowMins': [15, 30, 45], 'alarmUrgentMins': [30, 60, 90, 120], 'alarmWarnMins': [30, 60, 90, 120], 'alarmTimeagoWarn': True, 'alarmTimeagoWarnMins': '15', 'alarmTimeagoUrgent': True, 'alarmTimeagoUrgentMins': '30', 'alarmPumpBatteryLow': False, 'language': 'en', 'scaleY': 'log', 'showPlugins': 'careportal dbsize delta direction upbat', 'showForecast': 'ar2', 'focusHours': 3, 'heartbeat': 60, 'baseURL': '', 'authDefaultRoles': 'readable', 'thresholds': {'bgHigh': 180, 'bgTargetTop': 160, 'bgTargetBottom': 80, 'bgLow': 55}, 'insecureUseHttp': False, 'secureHstsHeader': True, 'secureHstsHeaderIncludeSubdomains': False, 'secureHstsHeaderPreload': False, 'secureCsp': False, 'deNormalizeDates': False, 'showClockDelta': False, 'showClockLastTime': False, 'frameUrl1': '', 'frameUrl2': '', 'frameUrl3': '', 'frameUrl4': '', 'frameUrl5': '', 'frameUrl6': '', 'frameUrl7': '', 'frameUrl8': '', 'frameName1': '', 'frameName2': '', 'frameName3': '', 'frameName4': '', 'frameName5': '', 'frameName6': '', 'frameName7': '', 'frameName8': '', 'authFailDelay': 5000, 'adminNotifiesEnabled': True, 'DEFAULT_FEATURES': ['bgnow', 'delta', 'direction', 'timeago', 'devicestatus', 'upbat', 'errorcodes', 'profile', 'bolus', 'dbsize', 'runtimestate', 'basal', 'careportal'], 'alarmTypes': ['simple'], 'enable': ['careportal', 'basal', 'dbsize', 'rawbg', 'iob', 'maker', 'cob', 'bwp', 'cage', 'iage', 'sage', 'boluscalc', 'pushover', 'treatmentnotify', 'loop', 'pump', 'profile', 'food', 'openaps', 'bage', 'alexa', 'override', 'speech', 'cors', 'bridge', 'treatmentnotify', 'bgnow', 'delta', 'direction', 'timeago', 'devicestatus', 'upbat', 'errorcodes', 'bolus', 'runtimestate', 'simplealarms']}, 'extendedSettings': {'bolus': {'renderOver': 1}, 'devicestatus': {'advanced': True, 'days': 1}}, 'authorized': None, 'runtimeState': 'loaded'}
Nightscout last uploaded basal: None
Nightscout last uploaded bolus: None

**Comment by jwoglom** [comment]
Hey, thanks for flagging this issue. I have bumped the version of tconnectsync and released a new version of tconnectsync-heroku.

**Comment by jwoglom** [comment]
Closing issue, please re-open at https://github.com/jwoglom/tconnectsync/issues if this is still an issue.
