### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by echampshi** [jwoglom/tconnectsync-heroku#9]
Hi very new to this.  Help would be appreciated.

tconnectsync version 0.7.1
Python version 3.9.9 (main, Nov 16 2021, 09:53:35) 
[GCC 9.3.0]
System platform linux
Running checks with time range 2022-04-08 21:07:26.544881 to 2022-04-09 21:07:26.544881
Current time: 2022-04-09 21:07:26.545131
time.tzname: ('UTC', 'UTC')
Loading secrets...
TIMEZONE_NAME: America/Chicago
-----
Logging in to t:connect ControlIQ API...
Received ApiException in ControlIQApi with endpoint 'tconnect/controliq/api/summary/users/c74b6f7d-ae12-4e91-94df-d5ff68302498' (tries 0): ControlIQ API HTTP 404 response: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-5bb29356ccdfda4694e7bb1223fdcd98-f72537c30be30046-00"} (HTTP 404)
Error occurred querying ControlIQ API for dashboard_summary:
ControlIQ API HTTP 404 response: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-5bb29356ccdfda4694e7bb1223fdcd98-f72537c30be30046-00"} (HTTP 404)
Querying ControlIQ therapy_timeline...
ControlIQ therapy_timeline: 
{'basal': {'algorithmDeliveryEvents': [],
           'profileDeliveryEvents': [],
           'profileRates': [],
           'tempDeliveryEvents': []},
 'events': [],
 'pumpFeatures': [{'features': {'controlIQ': {'dateTimeFirstDetected': '2020-03-20T11:59:58',
                                              'feature': 1,
                                              'unixTimestamp': 1584730798}},
                   'serialNumber': '656998'},
                  {'features': {'controlIQ': {'dateTimeFirstDetected': '2022-03-02T18:48:31',
                                              'feature': 1,
                                              'unixTimestamp': 1646275711}},
                   'serialNumber': '937778'},
                  {'features': {'controlIQ': {'dateTimeFirstDetected': '2021-05-06T21:26:32',
                                              'feature': 1,
                                              'unixTimestamp': 1620361592}},
                   'serialNumber': '90578354'}],
 'softwareUpdates': [],
 'suspensionDeliveryEvents': []}
ControlIQ processed therapy_timeline: 
[]
Querying ControlIQ therapy_events...
controliq therapy_events: 
{'dataOutOfRange': 0,
 'devices': 'T-Slim 4.3 (sn:000172), One-Touch BG Meter',
 'dst': 0,
 'event': [],
 'gapInData': 0,
 'noData': 1}
-----
Logging in to t:connect WS2 API...
WS2 basaliq status: 
{'BasalIQTech': {'AverageGlucoseOnResume': 0,
                 'AverageSuspensionDuration': 0,
                 'AverageSuspensionsPerDay': 0,
                 'AvgGlucoseOnSuspend': 0,
                 'AvgInactiveDays': 0,
                 'AvgInactiveHours': 0,
                 'AvgInactiveMinutes': 0,
                 'BiqDaysSetOff': 0,
                 'BiqHoursSetOff': 0,
                 'BiqMinutesSetOff': 0,
                 'BiqPercentSetOff': 0,
                 'CgmInactiveDays': 0,
                 'CgmInactiveHours': 0,
                 'CgmInactiveMinutes': 0,
                 'CgmInactivePercent': 0,
                 'DaysOn': 0,
                 'DaysSuspendedDay': 0,
                 'DaysSuspendedNight': 0,
                 'HoursOn': 0,
                 'HoursSuspendedDay': 0,
                 'HoursSuspendedNight': 0,
                 'MinutesSuspendedDay': 0,
                 'MinutesSuspendedNight': 0,
                 'PercentSuspendedDay': 0,
                 'PercentSuspendedNight': 0,
                 'PercentTimeOn': 0,
                 'PumpInactiveDays': 2,
                 'PumpInactiveHours': 0,
                 'PumpInactiveMinutes': 0,
                 'PumpInactivePercent': 100}}
Querying WS2 therapy_timeline_csv...
therapy_timeline_csv: 
{'basalData': [], 'bolusData': [], 'iobData': [], 'readingData': []}
-----

**Comment by jwoglom** [comment]
Hi @echampshi, would you mind answering these questions:

* When did you get your pump?
* Have you created an account on the tconnect website?
* Can you verify that with the tconnect credentials you've specified you can:
  * Log in to the Android or iOS app, with your pump paired and sending data
  * Log in at tconnect.tandemdiabetes.com and see your pump information appear

After that, if tconnectsync still gives this error, try:
* Resetting your password at tconnect.tandemdiabetes.com and setting it to the same password you use in the Android or iOS app
 * Downloading the Windows or MacOS tconnect uploader application and plug your pump into your computer to upload your settings.

If after completing one of these steps this solves the problem, please report back and let me know! This isn't the first report I've seen of odd behavior in tandem's API when trying to use tconnectsync for the first time, and other users have completed a combination of the above steps to get it working, but I'm not sure _exactly_ what fixes it.

**Comment by echampshi** [comment]
It's pulling data now without errors.  Thanks!

I have a new X2 pump received in March as a replacement.  I verified my tconnect credentials are the same online and app but deactivated several older pumps online.
I plugged in and used the updater.
